### ISSUE TITLE
Bug CameraPreview - Google Pixel

### ISSUE THREAD

**Issue by kkm** [koushick123/FlipCam#2]
I have a Google Pixel and CameraPreview is very dark, look at screenshot:
![Image of Yaktocat](https://i.imgur.com/a1rDEMx.png)

if I remove this code
`parameters.setPreviewFpsRange(MIN_FPS, MAX_FPS);`
in Camera1Manager.java (line number 126) then look better and bright.

I hope you can fix. thank you very much
greetz from swiss alp :)

**Comment by koushick123** [comment]
Hi,
I have made many more changes since Sep 19. Could you update your code and try to run in Google Pixel again? Let me know if you are still facing this issue.

I will take a look when time permits.

**Comment by kkm** [comment]
Sure, I am on vacation, will test with Pixel XL and Pixel 2 soon.
