### ISSUE TITLE
application close if you try to start a video recording in Android 5.1.1

### ISSUE THREAD

**Issue by shirou-jeff** [koushick123/FlipCam#4]
#### Expected behavior
The user expects to be able to use the function of video recorder to film what he want.

#### Actual behavior
The user cannot use the function of video recorder to film what you want. Because that when initiating a shot, the application closes unexpectedly.

#### How to reproduce
- Download the [application](https://play.google.com/store/apps/details?id=com.flipcam). 
- Install. 
- Open the application and try to start a recording. 
- After touching the "record" button we notice an unexpected closing.

* Browser: FlipCam V 1.01
* Operating system: Android 5.1.1

#### Recording Of The Bug
https://youtu.be/tHnpyOITGbw

**Comment by koushick123** [comment]
Hi,

Could you tell me on which device you have installed FlipCam?
Will take a look and get back.

**Comment by koushick123** [comment]
Hi,

A newer version 1.2 has been uploaded onto Play store. This issue should be resolved now.
