### ISSUE TITLE
Preview Screen Size doesn't fit the device screen size.

### ISSUE THREAD

**Issue by sachincool** [koushick123/FlipCam#5]
<div><h4>Expected behavior</h4>
<p>The preview should be able to adapt to any resolution of screen, and display fully on screen.</p>
<h4>Actual behavior</h4>
<p>A partial display is gotten on the screen, with blank spaces.</p>
<blockquote>
<p>This bug applies to screen with a large resolution such as 1280 * 800. When I tried using a device with 854 * 480, I was able to get a full preview.</p>
</blockquote>
<h4>How to reproduce</h4>
<p>Download flipcam on playstore <a href="https://play.google.com/store/apps/details?id=com.flipcam" target="_blank" rel="nofollow noopener">here</a>. Open app and check the preview for both photo and video modes.</p>
<h4>Working environment</h4>
<ul>
<li>App: flipcam version 1.01</li>
<li>Operating system:</li>
</ul>
<ol>
<li>Android 7.0 Nougat on Tecno K7 with resolution of 1280*800</li>
<li>Android 5.1 Lollipop tablet with resolution of 1216*800</li>
<li>Android 7.0 Nougat on Tecno W3 with resolution of 854*480</li>
</ol>
<h4>Recording Of The Bug</h4>
<p></p><center><img src="https://steemitimages.com/0x0/https://steemitimages.com/DQmdv4rm7dxMZnQY3TvW5uQfqfY2eFPijiZem4gzfp3EbKV/20180407_080117.gif" alt="20180407_080117.gif"></center>
<img src="https://cdn.utopian.io/posts/d5962cd2aefa5b941312fc18dc65cec359a5Screenshot_2018-04-11-19-47-25.png" alt="Screenshot_2018-04-11-19-47-25.png"><p></p>
<p><br></p>

**Comment by koushick123** [comment]
Hi,

Will take a look at this issue and get back.

**Comment by koushick123** [comment]
Hi,

Have released a newer version 1.2 onto Play store. The above issue should be resolved.
