### ISSUE TITLE
Icon-Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [koushick123/FlipCam#7]
Hi Sir @koushick123 , Good day! I am a graphic designer and I want to contribute to your amazing project by proposing a new Icon-Logo Design as I have noticed when going through your application that the icon is better to be updated in my opinion. By learning about the applications main feature I have come up with the designs below. If you like and want to use it I will be very glad to send you all the files needed as my gift fot the app for free. Please feel free to make suggestions or modification if you have something in mind. I also made the design fit for the latest softwares as I have created an adaptive icon also.

![idea explained](https://user-images.githubusercontent.com/36028424/39964546-48b51b6a-56b9-11e8-9caa-78bd190529c9.png)

Adaptive Icon (mock-up) for the newest softwares
![ezgif com-crop](https://user-images.githubusercontent.com/36028424/39964580-b14e07ae-56b9-11e8-8208-1a2e252602d7.gif)

Main Icon
![flipcam-01](https://user-images.githubusercontent.com/36028424/39964578-ad123688-56b9-11e8-97ac-379d38bc0e89.png)
Logotypes
![flipcam-02](https://user-images.githubusercontent.com/36028424/39964582-c49bc2d8-56b9-11e8-92fa-f935feb97142.png)
![flipcam-03](https://user-images.githubusercontent.com/36028424/39964583-c7b34a54-56b9-11e8-9008-c205c48f59e9.png)

I hope that you will like and use it for the app as it will bring more interests from the users,

Thanks and best regards,
-Tobaloidee

**Comment by koushick123** [comment]
Hi ,

Thank you so much for the logo you have designed. It looks really nice and more appealing. 

I am planing an update for Flipcam later in the year. 

Will definitely make use of your icon for that. 

Thanks again for the icon.  

Regards
Koushick S

**Comment by Tobaloidee** [comment]
Hi Sir..should I make a PR and send you the files? Im glad that you liked it..

**Comment by koushick123** [comment]
Hi,

You can send me the files. May I know what is a PR?

Thanks again. 

Regards
Koushick S

**Comment by Tobaloidee** [comment]
Hi Sir, I have finalized giving you all the needed files that you need for your new icon-logo.
you can get it all here in this link below. (PNG, AI, SVG, Adaptive Icon)

https://drive.google.com/drive/u/0/folders/1f-DltXeeEEF19v-pxEdrT0fDssQCuSoz

If you need something in the future just message me and i will attend to it. Thanks so much!!

Best regards!
-Tobaloidee

**Comment by koushick123** [comment]
Hi ,

I have downloaded all of the icons. You have a good amount of options. :+1: 
Thank you....
You don't need to address me as 'Hi Sir'.... :-)

I have merged your pull request.

**Comment by Tobaloidee** [comment]
haha..I am just grateful and happy to have contributed to your great project! Im looking forward to working with you again.. :)

Thanks so much!

**Comment by koushick123** [comment]
Closing issue.
